const $ = (selector) => document.querySelector(selector);
const dialog = $('#gameDialog');
const canvas = $('#gameCanvas');
const ctx = canvas.getContext('2d');
const overlay = $('#gameOverlay');
const title = $('#gameTitle');
const type = $('#gameType');
const scoreEl = $('#score');
const bestEl = $('#best');
const startButton = $('#startGame');
const controls = $('#gameControls');
const memoryBoard = $('#memoryBoard');
const toast = $('#toast');
let game = null, raf = null, soundOn = false, audioCtx = null;
const games = {
  neon: { title: 'Neon Dodge', type: 'ARCADE • 1 PLAYER', best: 'orbit-neon-best', intro: ['Catch the glow.', 'Move with <kbd>←</kbd> <kbd>→</kbd> or your mouse. Avoid the falling shards.'], controls: '<span><kbd>←</kbd><kbd>→</kbd> move</span><span>Last as long as you can</span>' },
  breaker: { title: 'Brick Bloom', type: 'CLASSIC • 1 PLAYER', best: 'orbit-breaker-best', intro: ['Clear the bloom.', 'Move with <kbd>←</kbd> <kbd>→</kbd> or your mouse. Break every brick.'], controls: '<span><kbd>←</kbd><kbd>→</kbd> move</span><span>Clear all 24 bricks</span>' },
  memory: { title: 'Pixel Pairs', type: 'PUZZLE • 1 PLAYER', best: 'orbit-memory-best', intro: ['Find all four pairs.', 'Tap any two tiles to reveal them. Fewer moves means a better score.'], controls: '<span>Tap cards to flip</span><span>Find every pair</span>' }
};

function bestFor(key) { try { return Number(localStorage.getItem(games[key].best) || 0); } catch { return 0; } }
function setScore(value) { scoreEl.textContent = String(Math.max(0, Math.floor(value))).padStart(4, '0'); }
function setBest(key) { bestEl.textContent = String(bestFor(key)).padStart(4, '0'); }
function tone(freq = 440, duration = .06) { if (!soundOn) return; try { audioCtx ||= new AudioContext(); const o = audioCtx.createOscillator(), g = audioCtx.createGain(); o.frequency.value = freq; g.gain.setValueAtTime(.06, audioCtx.currentTime); g.gain.exponentialRampToValueAtTime(.001, audioCtx.currentTime + duration); o.connect(g).connect(audioCtx.destination); o.start(); o.stop(audioCtx.currentTime + duration); } catch {} }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2300); }
function resizeCanvas() { const ratio = Math.min(2, devicePixelRatio || 1); const rect = canvas.getBoundingClientRect(); canvas.width = Math.round(rect.width * ratio); canvas.height = Math.round(rect.height * ratio); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); return { w: rect.width, h: rect.height }; }
function drawBackground(w, h) { ctx.fillStyle = '#242c4c'; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = '#98a4e026'; ctx.lineWidth = 1; for(let x=0;x<w;x+=36){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()} for(let y=0;y<h;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()} }
function finish(key, score, message) { cancelAnimationFrame(raf); raf = null; const best = bestFor(key); if (score > best) { try { localStorage.setItem(games[key].best, score); } catch {} setBest(key); message += ' New personal best!'; } overlay.querySelector('#overlayLabel').textContent = score > best ? 'NEW BEST' : 'ROUND COMPLETE'; overlay.querySelector('#overlayTitle').textContent = message; overlay.querySelector('#overlayHelp').innerHTML = `Score: <strong>${Math.floor(score)}</strong>`; startButton.textContent = 'Play again →'; overlay.hidden = false; tone(190, .12); }
function openGame(key) { cancelAnimationFrame(raf); game = key; title.textContent = games[key].title; type.textContent = games[key].type; setScore(0); setBest(key); overlay.querySelector('#overlayLabel').textContent = 'READY?'; overlay.querySelector('#overlayTitle').textContent = games[key].intro[0]; overlay.querySelector('#overlayHelp').innerHTML = games[key].intro[1]; startButton.textContent = 'Start game →'; overlay.hidden = false; controls.innerHTML = games[key].controls; memoryBoard.hidden = key !== 'memory'; canvas.style.display = key === 'memory' ? 'none' : 'block'; if (key !== 'memory') { resizeCanvas(); paintIdle(key); } dialog.showModal(); }
function paintIdle(key) { const {w,h}=resizeCanvas(); drawBackground(w,h); ctx.textAlign='center'; ctx.fillStyle='#d9ff45'; ctx.font='600 13px DM Mono'; ctx.fillText(key === 'neon' ? 'STAY IN THE LIGHT' : 'BREAK THE BLOOM',w/2,h/2); }

function startNeon() { overlay.hidden = true; const {w,h}=resizeCanvas(); let player={x:w/2,y:h-42,w:44}, shards=[], start=performance.now(), last=start, pointer=w/2; const keys={}; const move=(e)=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight')keys[e.key]=e.type==='keydown'}; const mouse=(e)=>{const r=canvas.getBoundingClientRect();pointer=e.clientX-r.left}; addEventListener('keydown',move); addEventListener('keyup',move); canvas.addEventListener('pointermove',mouse);
  const loop=(now)=>{const dt=Math.min(32,now-last)/16;last=now; const elapsed=(now-start)/1000, score=elapsed*110; if(keys.ArrowLeft)player.x-=8*dt;if(keys.ArrowRight)player.x+=8*dt; player.x+=(pointer-player.x)*.1;player.x=Math.max(player.w/2+5,Math.min(w-player.w/2-5,player.x)); if(Math.random()<.045+elapsed*.003)shards.push({x:Math.random()*w,y:-18,r:8+Math.random()*9,spd:3+Math.random()*4+elapsed*.09,spin:Math.random()*6}); for(const s of shards){s.y+=s.spd*dt;s.spin+=.08*dt} shards=shards.filter(s=>s.y<h+30); drawBackground(w,h); ctx.fillStyle='#d9ff45';ctx.shadowColor='#d9ff45';ctx.shadowBlur=15;ctx.beginPath();ctx.arc(player.x,player.y,14,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#d9ff45';ctx.fillRect(player.x-player.w/2,player.y+18,player.w,5); for(const s of shards){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.spin);ctx.fillStyle='#ff7474';ctx.shadowColor='#ff7474';ctx.shadowBlur=12;ctx.fillRect(-s.r,-s.r,s.r*2,s.r*2);ctx.restore(); if(Math.abs(s.x-player.x)<s.r+20&&Math.abs(s.y-player.y)<s.r+18){removeEventListener('keydown',move);removeEventListener('keyup',move);canvas.removeEventListener('pointermove',mouse);setScore(score);finish('neon',score,'Nice run.');return}} ctx.fillStyle='#fff';ctx.font='500 11px DM Mono';ctx.textAlign='left';ctx.fillText(`TIME ${elapsed.toFixed(1)}s`,18,28);setScore(score);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop); }
function startBreaker() { overlay.hidden=true; const {w,h}=resizeCanvas();let paddle=w/2,ball={x:w/2,y:h-75,vx:4,vy:-4,r:8},pointer=w/2,score=0,last=performance.now();const keys={};const bricks=[];const cols=6,bw=(w-72)/cols;for(let r=0;r<4;r++)for(let c=0;c<cols;c++)bricks.push({x:30+c*bw,y:48+r*35,w:bw-7,h:23,live:true,color:['#ff7474','#d9ff45','#8d7aff','#4fb9ae'][r]});const move=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight')keys[e.key]=e.type==='keydown'};const mouse=e=>{const r=canvas.getBoundingClientRect();pointer=e.clientX-r.left};addEventListener('keydown',move);addEventListener('keyup',move);canvas.addEventListener('pointermove',mouse);
 const clean=()=>{removeEventListener('keydown',move);removeEventListener('keyup',move);canvas.removeEventListener('pointermove',mouse)};const loop=now=>{const dt=Math.min(30,now-last)/16;last=now;if(keys.ArrowLeft)paddle-=8*dt;if(keys.ArrowRight)paddle+=8*dt;paddle+=(pointer-paddle)*.09;paddle=Math.max(45,Math.min(w-45,paddle));ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<ball.r||ball.x>w-ball.r){ball.vx*=-1;tone(310)}if(ball.y<ball.r){ball.vy*=-1;tone(310)}if(ball.y>h+20){clean();setScore(score);finish('breaker',score,'The bloom won this time.');return}if(ball.y>h-48&&ball.y<h-28&&Math.abs(ball.x-paddle)<52&&ball.vy>0){ball.vy=-Math.abs(ball.vy);ball.vx+=(ball.x-paddle)/34;tone(430)}for(const b of bricks)if(b.live&&ball.x+ball.r>b.x&&ball.x-ball.r<b.x+b.w&&ball.y+ball.r>b.y&&ball.y-ball.r<b.y+b.h){b.live=false;ball.vy*=-1;score+=100;tone(640,.04);break}drawBackground(w,h);for(const b of bricks)if(b.live){ctx.fillStyle=b.color;ctx.fillRect(b.x,b.y,b.w,b.h)}ctx.fillStyle='#fff';ctx.fillRect(paddle-45,h-30,90,8);ctx.beginPath();ctx.fillStyle='#d9ff45';ctx.arc(ball.x,ball.y,ball.r,0,7);ctx.fill();setScore(score);if(!bricks.some(b=>b.live)){clean();finish('breaker',score,'Board cleared!');return}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop)}
function startMemory(){overlay.hidden=true;memoryBoard.hidden=false;memoryBoard.innerHTML='';let icons=['✦','✦','●','●','◆','◆','☻','☻'].sort(()=>Math.random()-.5),open=[],moves=0,matched=0;setScore(0);icons.forEach((icon,i)=>{const card=document.createElement('button');card.className='memory-card';card.setAttribute('aria-label','Flip card');card.innerHTML=`<div><span class="front">?</span><span class="back">${icon}</span></div>`;card.onclick=()=>{if(open.length===2||card.classList.contains('flipped')||card.classList.contains('matched'))return;card.classList.add('flipped');open.push({card,icon});tone(430,.035);if(open.length===2){moves++;setScore(Math.max(0,1000-moves*45));if(open[0].icon===open[1].icon){open.forEach(x=>x.card.classList.add('matched'));open=[];matched++;tone(730,.08);if(matched===4)setTimeout(()=>finish('memory',Math.max(0,1000-moves*45),moves<=5?'Perfect memory!':'All pairs found!'),350)}else{setTimeout(()=>{open.forEach(x=>x.card.classList.remove('flipped'));open=[]},700)}}};memoryBoard.append(card)})}
startButton.addEventListener('click',()=>{ if(game==='neon')startNeon(); if(game==='breaker')startBreaker(); if(game==='memory')startMemory();});
document.querySelectorAll('[data-play]').forEach(button=>button.addEventListener('click',()=>openGame(button.dataset.play)));
$('#closeGame').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{cancelAnimationFrame(raf);raf=null});
$('#soundToggle').addEventListener('click',()=>{soundOn=!soundOn;$('#soundToggle').textContent=soundOn?'♫':'♪';$('#soundToggle').setAttribute('aria-label',soundOn?'Turn sound off':'Turn sound on');showToast(soundOn?'Sound on':'Sound off');tone(520,.08)});
$('#year').textContent=new Date().getFullYear(); $('#heroBest').textContent=(bestFor('neon')||2480).toLocaleString();
